<a href="https://colab.research.google.com/github/Nada-Naveesh/Machine_Learning/blob/main/pickle_joblib4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("homeprice.csv")


In [19]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)
model.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [13]:
#Save Model To a File Using Python Pickle
import pickle
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [14]:
#Load Saved Model
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [15]:
mp.coef_

array([135.78767123])

In [16]:
mp.intercept_

np.float64(180616.43835616432)

In [17]:
mp.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [29]:
#Save Trained Model Using joblib
import joblib
joblib.dump(model, 'model_joblib')

['model_joblib']

In [30]:
#Load Saved Model
mj = joblib.load('model_joblib')

In [31]:
mj.coef_

array([135.78767123])

In [33]:
mj.intercept_

np.float64(180616.43835616432)

In [35]:
mj.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])